development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: my_own_development
  pool: 5
  username: root
  password: password

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: my_own_test
  pool: 5
  username: root
  password: password
